Time::DATE_FORMATS[:jp] = "%Y年%m月%d日 %H時%M分"
Time::DATE_FORMATS[:jpl] = "%Y年%m月%d日 %H時%M分%S秒"
Time::DATE_FORMATS[:jps] = "%m月%d日 %H時%M分"
Time::DATE_FORMATS[:s] = "%m/%d %H:%M"
Time::DATE_FORMATS[:m] = "%Y/%m/%d %H:%M"
Time::DATE_FORMATS[:l] = "%Y/%m/%d %H:%M:%S"
